apiVersion: v1
kind: Pod
metadata:
  labels:
    run: demo-web
  name: demo-web
spec:
  volumes: # Define the volume emptyDir
  - name: html
    emptyDir: {}
  initContainers: # Initialization container that clones git repo to emptyDir
  - image: alpine/git:1.0.17
    name: git-clone
    command: ['/bin/sh', '-c']
    args: ['git clone https://github.com/cloudacademy/static-website-example /html']
    volumeMounts:
    - name: html
      mountPath: /html/
  containers:
  - image: nginx
    name: website-from-repo
    volumeMounts: # Will have the git repo from the init container available
    - name: html
      mountPath: /usr/share/nginx/html
